### ISSUE TITLE
No option to specify log path

### ISSUE THREAD

**Issue by ma7moudat** [jamesdbloom/mockserver-node#18]
While working with `verbose: true`, a `mockserver.log` file is created in the directory from which the server was started. Shouldn't there be an option to specify another path for the log file?

**Comment by jamesdbloom** [comment]
In the new release of MockServer (in the new week or so) no log file will be created, all output will be to the console out, so this will no longer be an issue.  If you want the log output to go to a file you can just pipe the output for example:
```bash
grunt start_mockserver --verbose > mockserver.log
```
In addition, all the logs and history is available via a REST API or through the clients as documented: http://mock-server.com/mock_server/debugging_issues.html
